// Code generated by MockGen. DO NOT EDIT.
// Source: transport.go
//
// Generated by this command:
//
//	mockgen -source=transport.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contract "github.com/ananaslegend/reposeetory/internal/notifications/contract"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendConfirmation mocks base method.
func (m *MockSender) SendConfirmation(ctx context.Context, p contract.SendConfirmationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmation", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmation indicates an expected call of SendConfirmation.
func (mr *MockSenderMockRecorder) SendConfirmation(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmation", reflect.TypeOf((*MockSender)(nil).SendConfirmation), ctx, p)
}

// SendRelease mocks base method.
func (m *MockSender) SendRelease(ctx context.Context, p contract.SendReleaseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRelease", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRelease indicates an expected call of SendRelease.
func (mr *MockSenderMockRecorder) SendRelease(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRelease", reflect.TypeOf((*MockSender)(nil).SendRelease), ctx, p)
}
