// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -source=notifier.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notifier "github.com/ananaslegend/reposeetory/internal/notifier"
	domain "github.com/ananaslegend/reposeetory/internal/subscription/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ProcessNext mocks base method.
func (m *MockRepository) ProcessNext(ctx context.Context, fn func(context.Context, notifier.PendingNotification) error) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNext", ctx, fn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessNext indicates an expected call of ProcessNext.
func (mr *MockRepositoryMockRecorder) ProcessNext(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNext", reflect.TypeOf((*MockRepository)(nil).ProcessNext), ctx, fn)
}

// MockMailSender is a mock of MailSender interface.
type MockMailSender struct {
	ctrl     *gomock.Controller
	recorder *MockMailSenderMockRecorder
	isgomock struct{}
}

// MockMailSenderMockRecorder is the mock recorder for MockMailSender.
type MockMailSenderMockRecorder struct {
	mock *MockMailSender
}

// NewMockMailSender creates a new mock instance.
func NewMockMailSender(ctrl *gomock.Controller) *MockMailSender {
	mock := &MockMailSender{ctrl: ctrl}
	mock.recorder = &MockMailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailSender) EXPECT() *MockMailSenderMockRecorder {
	return m.recorder
}

// SendRelease mocks base method.
func (m *MockMailSender) SendRelease(ctx context.Context, p domain.SendReleaseParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRelease", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRelease indicates an expected call of SendRelease.
func (mr *MockMailSenderMockRecorder) SendRelease(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRelease", reflect.TypeOf((*MockMailSender)(nil).SendRelease), ctx, p)
}
