// Code generated by MockGen. DO NOT EDIT.
// Source: scanner.go
//
// Generated by this command:
//
//	mockgen -source=scanner.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/ananaslegend/reposeetory/internal/github"
	domain "github.com/ananaslegend/reposeetory/internal/subscription/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetRepositoriesWithLock mocks base method.
func (m *MockRepository) GetRepositoriesWithLock(ctx context.Context, limit int) ([]domain.GitHubRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesWithLock", ctx, limit)
	ret0, _ := ret[0].([]domain.GitHubRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesWithLock indicates an expected call of GetRepositoriesWithLock.
func (mr *MockRepositoryMockRecorder) GetRepositoriesWithLock(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesWithLock", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesWithLock), ctx, limit)
}

// InsertNotifications mocks base method.
func (m *MockRepository) InsertNotifications(ctx context.Context, repoID int64, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertNotifications", ctx, repoID, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertNotifications indicates an expected call of InsertNotifications.
func (mr *MockRepositoryMockRecorder) InsertNotifications(ctx, repoID, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNotifications", reflect.TypeOf((*MockRepository)(nil).InsertNotifications), ctx, repoID, tag)
}

// UpsertLastSeen mocks base method.
func (m *MockRepository) UpsertLastSeen(ctx context.Context, repoID int64, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLastSeen", ctx, repoID, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertLastSeen indicates an expected call of UpsertLastSeen.
func (mr *MockRepositoryMockRecorder) UpsertLastSeen(ctx, repoID, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLastSeen", reflect.TypeOf((*MockRepository)(nil).UpsertLastSeen), ctx, repoID, tag)
}

// MockReleaseProvider is a mock of ReleaseProvider interface.
type MockReleaseProvider struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseProviderMockRecorder
	isgomock struct{}
}

// MockReleaseProviderMockRecorder is the mock recorder for MockReleaseProvider.
type MockReleaseProviderMockRecorder struct {
	mock *MockReleaseProvider
}

// NewMockReleaseProvider creates a new mock instance.
func NewMockReleaseProvider(ctrl *gomock.Controller) *MockReleaseProvider {
	mock := &MockReleaseProvider{ctrl: ctrl}
	mock.recorder = &MockReleaseProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseProvider) EXPECT() *MockReleaseProviderMockRecorder {
	return m.recorder
}

// GetLatestReleases mocks base method.
func (m *MockReleaseProvider) GetLatestReleases(ctx context.Context, p github.GetLatestReleasesParams) (map[int64]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestReleases", ctx, p)
	ret0, _ := ret[0].(map[int64]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestReleases indicates an expected call of GetLatestReleases.
func (mr *MockReleaseProviderMockRecorder) GetLatestReleases(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestReleases", reflect.TypeOf((*MockReleaseProvider)(nil).GetLatestReleases), ctx, p)
}
