// Code generated by MockGen. DO NOT EDIT.
// Source: scanner.go
//
// Generated by this command:
//
//	mockgen -source=scanner.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/ananaslegend/reposeetory/internal/github"
	scanner "github.com/ananaslegend/reposeetory/internal/scanner"
	domain "github.com/ananaslegend/reposeetory/internal/subscription/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockRepository) RunInTx(ctx context.Context, limit int, fn func(context.Context, []domain.GitHubRepo) ([]scanner.ScanResult, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, limit, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockRepositoryMockRecorder) RunInTx(ctx, limit, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockRepository)(nil).RunInTx), ctx, limit, fn)
}

// MockReleaseProvider is a mock of ReleaseProvider interface.
type MockReleaseProvider struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseProviderMockRecorder
	isgomock struct{}
}

// MockReleaseProviderMockRecorder is the mock recorder for MockReleaseProvider.
type MockReleaseProviderMockRecorder struct {
	mock *MockReleaseProvider
}

// NewMockReleaseProvider creates a new mock instance.
func NewMockReleaseProvider(ctrl *gomock.Controller) *MockReleaseProvider {
	mock := &MockReleaseProvider{ctrl: ctrl}
	mock.recorder = &MockReleaseProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseProvider) EXPECT() *MockReleaseProviderMockRecorder {
	return m.recorder
}

// GetLatestReleases mocks base method.
func (m *MockReleaseProvider) GetLatestReleases(ctx context.Context, p github.GetLatestReleasesParams) (map[int64]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestReleases", ctx, p)
	ret0, _ := ret[0].(map[int64]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestReleases indicates an expected call of GetLatestReleases.
func (mr *MockReleaseProviderMockRecorder) GetLatestReleases(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestReleases", reflect.TypeOf((*MockReleaseProvider)(nil).GetLatestReleases), ctx, p)
}
