// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ananaslegend",
            "url": "https://github.com/ananaslegend/reposeetory"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Subscription form (HTML).",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "pages"
                ],
                "summary": "Landing page",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/confirm/{token}": {
            "get": {
                "description": "Confirms a subscription using the one-time token from the confirmation email (valid 24h).",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Confirm subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Confirmation token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "token not found"
                    },
                    "410": {
                        "description": "token expired"
                    }
                }
            }
        },
        "/api/subscribe": {
            "post": {
                "description": "Subscribe to GitHub repository release notifications. A confirmation email will be sent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Subscribe to a repository",
                "parameters": [
                    {
                        "description": "Subscription request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.SubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "already subscribed",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/subscriptions": {
            "get": {
                "description": "Returns all confirmed subscriptions for a given email address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List active subscriptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.SubscriptionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_subscription_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/unsubscribe/{token}": {
            "get": {
                "description": "Unsubscribes and permanently removes all subscription data (GDPR hard delete).",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Unsubscribe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unsubscribe token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "token not found"
                    }
                }
            }
        },
        "/subscribed": {
            "get": {
                "description": "Shown after a successful subscription form submission (HTML).",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "pages"
                ],
                "summary": "Subscribed success page",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_subscription_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid email"
                }
            }
        },
        "internal_subscription_http.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "pending_confirmation"
                }
            }
        },
        "internal_subscription_http.SubscribeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "repository": {
                    "type": "string",
                    "example": "ananaslegend/reposeetory"
                }
            }
        },
        "internal_subscription_http.SubscriptionItem": {
            "type": "object",
            "properties": {
                "confirmed_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "repository": {
                    "type": "string",
                    "example": "ananaslegend/reposeetory"
                }
            }
        },
        "internal_subscription_http.SubscriptionsResponse": {
            "type": "object",
            "properties": {
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_subscription_http.SubscriptionItem"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "reposeetory.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Reposeetory API",
	Description:      "GitHub Release Notification API. Subscribe to repositories and get email notifications on new releases.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
